[package]
name = "voice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
pitch_shift = "1.0.0"
random = "0.14.0"
rodio = "0.17.1"
