[package]
name = "voice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pitch_shift = "1.0.0"
rand = "0.8.5"
rodio = "0.17.1"
vader_sentiment = "0.1.1"
